# Generated by Django 5.0.6 on 2024-05-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=10, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
